# Notebook Laboratorio 3 Bases de Datos Avanzadas - Neo4J

Descarga de librería

In [16]:
%pip install neo4j

Requirement already satisfied: neo4j in c:\Users\Bruno\AppData\Local\Programs\Python\Python311\Lib\site-packages (6.2.0)
Requirement already satisfied: pytz in c:\Users\Bruno\AppData\Local\Programs\Python\Python311\Lib\site-packages (from neo4j) (2025.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

## 1. Librerías y dependencias

In [17]:
import pandas as pd
from neo4j import GraphDatabase

## 2. Conexión y creación de BD Neo4J

In [18]:
URI = "bolt://localhost:7687"
AUTH = ("neo4j", "password123")
driver = GraphDatabase.driver(URI, auth=AUTH)
session = driver.session()

Si quieren trabajar con ver el grafo deben abrir Neo4j Browser. Este esta en http://localhost:7474/browser/.

Para entrar deben ingresar el usuario y contraseña, lo que esta en el AUTH

## 3. Procesamiento y Poblamiento de la BD Neo4J

In [19]:
# Celda de limpieza: Borra todos los nodos y relaciones del grafo
query_limpieza = "MATCH (n) DETACH DELETE n"

session.run(query_limpieza)
print("¡Grafo limpiado por completo! Listo para probar el nuevo ciclo for.")

¡Grafo limpiado por completo! Listo para probar el nuevo ciclo for.

In [20]:
# 1. Cargamos el dataset
df = pd.read_csv('normativas/normativas_clasificadas_IA.csv')
df.fillna("", inplace=True)

# 2. Definimos reglas de referencia
reglas_referencia = {
    "Resolución Exenta N° 176 de 2020": "Resolución 176 de 2020",
    "Resolución Exenta N° 76 de 2021": "Resolución 76 de 2021",
    "Resolución Exenta N° 79 de 2025": "Resolución 79 de 2025",
    "Resolución N° 59 de 2025": "Resolución 59 de 2025",
    "Circular N° 38 de 2025": "Circular 38 de 2025",
    "Articulo 68 del Código Tributario": "Articulo 68 del Código Tributario"
}

# 3. Definimos reglas de palabras
reglas_palabras = {
    "boleta": "Contiene 'boleta'",
    "comprobante electrónico": "Contiene 'comprobante electrónico'",
    "registro de compra": "Contiene 'registro de compra'",
    "registro de venta": "Contiene 'registro de venta'",
    "cumplimiento tributario": "Contiene 'cumplimiento tributario'",
    "inicio de actividades": "Contiene 'inicio de actividades'",
    "medios de pago electrónicos": "Contiene 'medios de pago electrónicos'",
    "pos": "Contiene 'POS'",
    "p.o.s": "Contiene 'P.O.S'",
    "puntos de venta": "Contiene 'puntos de venta'",
    "operadores y administradores": "Contiene 'operadores y administradores'",
    "comercio electrónico": "Contiene 'comercio electrónico'"
}

# 4. Recorremos filas del Dataset
for index, row in df.iterrows():
    # Extraemos todos los datos de la fila
    nombre = str(row['name'])
    desc = str(row['description'])
    fuente = str(row['fuente'])
    url = str(row['url'])
    tipo_doc = str(row['tipo_documento'])
    cuerpo = str(row['cuerpo'])
    relevancia = str(row['relevancia'].strip())

    if relevancia == "No Relevante":
        relevancia = "NoRelevante"
    elif relevancia == "Relevante":
        relevancia = "Relevante"

    explicacion = str(row['explicacion'])
    
    # Armamos el texto con toda la informacion sobre la normativa
    texto_completo = f"{nombre} {desc} {cuerpo} {explicacion}"
    texto_lower = texto_completo.lower()

    # 5. Revisamos si la normativa activa alguna regla de palabra o de referencia y las agregamos a una lista
    reglas_activadas = []
    
    for ref, regla in reglas_referencia.items():
        if ref.lower() in texto_lower:
            reglas_activadas.append((regla, f"Se detectó la referencia: {ref}"))
            
    for palabra, regla in reglas_palabras.items():
        if palabra.lower() in texto_lower:
            reglas_activadas.append((regla, f"Se detectó la palabra clave: {palabra}"))
    
    # 6. Clasificamos este registro con LABELS de NEO4J
    ## El registro puntual tiene una coleccion de labels
    labels = ["Normativa"]

    if "Circular" in tipo_doc: 
        labels.append("Circular")

    if "Resolución" in tipo_doc or "Resolucion" in tipo_doc: 
        labels.append("Resolucion")
    
    labels.append(relevancia)

    if relevancia == "Relevante":
        if len(reglas_activadas) > 0:
            labels.append("ExplicacionValida")
        else:
            labels.append("ExplicacionDebil")
            labels.append("RequiereRevision")

    else:  
        if len(reglas_activadas) == 0:
            labels.append("ExplicacionValida")
        else:
            labels.append("RequiereRevision")
            
    labels_str = ":".join(labels)

    # 7. Creamos la query para agregar el registro y sus labels a la BD
    query_base = f"""
    MERGE (agente:AgenteIANormativo {{nombre: 'Agente IA Normativo'}})
    MERGE (f:Fuente {{nombre: $fuente}})
    MERGE (n:{labels_str} {{nombre: $nombre}})
      SET n.descripcion = $desc, 
          n.url = $url, 
          n.cuerpo = $cuerpo
          
    MERGE (n)-[:EMITIDA_POR]->(f)
    MERGE (n)-[:CLASIFICADA_POR]->(agente)
    
    CREATE (exp:ExplicacionIA {{texto: $explicacion}})
    MERGE (n)-[:TIENE_EXPLICACION]->(exp)
    """
    session.run(query_base, fuente=fuente, nombre=nombre, desc=desc, url=url, cuerpo=cuerpo, explicacion=explicacion)
    
    # 8. Agregamos a la BD una justificación de la regla de negocio activada y el por qué se activó
    for regla_nombre, evidencia in reglas_activadas:
        query_reglas = """
        MATCH (n:Normativa {nombre: $nombre})
        MERGE (r:ReglaDeNegocio {nombre: $regla_nombre})
        MERGE (n)-[:ACTIVA_REGLA]->(r)
        
        CREATE (ev:EvidenciaTextual {texto: $evidencia})
        MERGE (n)-[:RESPALDADA_POR]->(ev)
        """
        session.run(query_reglas, nombre=nombre, regla_nombre=regla_nombre, evidencia=evidencia)

## 4. Consultas obligatorias

### 4.1 Consulta de clasificación general:
**Visualizar normativas Relevantes y No Relevantes con nombre, tipo documental, fuente, descripción y explicación IA.**

In [21]:
# Consulta 1: Clasificación general
q1 = """
MATCH (n:Normativa)-[:TIENE_EXPLICACION]->(e:ExplicacionIA)
MATCH (n)-[:EMITIDA_POR]->(f:Fuente)
RETURN n.nombre AS Normativa, 
       labels(n) AS Etiquetas, 
       f.nombre AS Fuente, 
       n.descripcion AS Descripcion,
       e.texto AS Explicacion_IA
LIMIT 10
"""
res1 = session.run(q1)
df1 = pd.DataFrame([r.data() for r in res1])
df1

,Normativa,Etiquetas,Fuente,Descripcion,Explicacion_IA
0,Resolución Exenta SII N° 68 del 19 de Junio del 2025,"[Normativa, NoRelevante, RequiereRevision, Resolucion]",Fuente: Subdireccion Normativa,Crea la oficina de relaciones internacionales.,"La normativa se centra en la creación de una oficina de relaciones internacionales dentro del Servicio de Impuestos Internos, lo cual no se relaciona directamente con boletas, comprobantes electrónicos, registros de compra o venta, cumplimiento tributario, inicio de actividades, medios de pago electrónicos, POS, operadores y administradores, o comercio electrónico. No cumple reglas de negocio."
1,Resolución Exenta SII N° 33 del 13 de Marzo del 2025,"[Normativa, NoRelevante, RequiereRevision, Resolucion]",Fuente: Subdireccion Normativa,Establece escala de tasas conforme al precio internacional de los minerales que se indican y para los efectos que se señalan.,No cumple reglas de negocio.
2,Resolución Exenta SII N° 01 del 02 de Enero del 2025,"[Normativa, NoRelevante, RequiereRevision, Resolucion]",Fuente: Subdireccion Normativa,Crea registro de pequeños artesanos exonerados de IVA en las ventas de productos que elaboren con materias primas.,"No cumple reglas de negocio. La normativa se centra en la creación de un registro de pequeños artesanos exonerados de IVA, lo cual no se relaciona directamente con los temas especificados como boletas, comprobantes electrónicos, registro de compra, registro de venta, cumplimiento tributario, inicio de actividades, medios de pago electrónicos, POS, operadores y administradores, o comercio electrónico."
3,Circular N° 9 del 30 de Enero del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]",Fuente: Subdireccion Normativa,"Informa datos relacionados con la aplicación del sistema de corrección monetaria; reajustabilidad de los saldos de los registros de rentas empresariales, del registro FUR y de los excesos de retiros no imputados y tablas de impuesto global complementario correspondientes al año tributario 2025.","La normativa se centra en la aplicación del sistema de corrección monetaria, reajustabilidad de registros de rentas empresariales y tablas de impuesto global complementario, sin abordar temas directamente relacionados con boletas, comprobantes electrónicos, registros de compra o venta, cumplimiento tributario automatizado, inicio de actividades, medios de pago electrónicos, POS, operadores y administradores, o comercio electrónico."
4,Circular N° 5 del 10 de Enero del 2025,"[Normativa, Circular, NoRelevante, ExplicacionValida]",Fuente: Subdireccion Normativa,"Operaciones de crédito de dinero. Valor de la Unidad de Fomento para los días comprendidos entre el 10 de enero de 2025 y el 9 de febrero de 2025, ambos inclusive.","La normativa se refiere al valor de la Unidad de Fomento para un período específico, lo cual no está relacionado con los temas definidos como relevantes para el sistema de cumplimiento normativo automatizado de la fintech. No cumple reglas de negocio."
5,Circular N° 41 del 09 de Mayo del 2025,"[Normativa, Circular, NoRelevante, ExplicacionValida]",Fuente: Subdireccion Normativa,"Operaciones de crédito de dinero. Valor de la Unidad de Fomento para los días comprendidos entre el 10 de mayo de 2025 y el 9 de junio de 2025, ambos inclusive.",La normativa se refiere al valor de la Unidad de Fomento para un período específico y no trata explícitamente ninguno de los temas definidos como relevantes para el sistema de cumplimiento normativo automatizado de la fintech.
6,Circular N° 40 del 09 de Mayo del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]",Fuente: Subdireccion Normativa,Tablas de impuesto único de segunda categoría para el mes de junio de 2025 e información adicional relacionada con dicho tributo.,"La normativa se centra en las tablas de impuesto único de segunda categoría y no aborda temas relacionados con boletas, comprobantes electrónicos, registros de compra o venta, cumplimiento tributario automatizado, inicio de actividades, medios de pago electrónicos, POS, operadores y administradores, o comercio electrónico."
7,Circular N° 4 del 09 de Enero del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]",Fuente: Subdireccion Normativa,Tablas de impuesto único de segunda categoría para el mes de febrero de 2025 e información adicional relacionada con dicho tributo,"La normativa se centra en las tablas de impuesto único de segunda categoría y no aborda ninguno de los temas específicos relacionados con el cumplimiento tributario automatizado de una fintech, como boletas, comprobantes electrónicos, registros de compra o venta, medios de pago electrónicos, entre otros."
8,Circular N° 3 del 09 de Enero del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]",Fuente: Subdireccion Normativa,"Informa sobre modificación introducida por la letra c) del N° 14 del artículo 4 de la Ley N° 21.713 al artículo 152 de la Ordenanza de Aduanas, en materia de impuesto a las donaciones.","La normativa se centra en la modificación de disposiciones relacionadas con el impuesto a las donaciones y la exención de ciertos trámites para donaciones de mercancías, lo cual no se relaciona directamente con los temas definidos como relevantes para el sistema de cumplimiento normativo automatizado de la fintech."
9,Circular N° 29 del 10 de Abril del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]",Fuente: Subdireccion Normativa,"Informa porcentaje de reajuste a aplicar a los impuestos anuales a la renta a declarar y pagar en el año tributario 2025, de acuerdo con lo dispuesto en el artículo 72 de la Ley sobre Impuesto a la Renta.","La normativa se refiere al porcentaje de reajuste a aplicar a los impuestos anuales a la renta, lo cual no está relacionado con los temas específicos de boletas, comprobantes electrónicos, registro de compra, registro de venta, cumplimiento tributario, inicio de actividades, medios de pago electrónicos, POS, operadores y administradores, o comercio electrónico. No cumple reglas de negocio."

**Probar la consulta en Neo4j Browser**

```cypher
MATCH (n:Normativa)-[r1:TIENE_EXPLICACION]->(e:ExplicacionIA)
MATCH (n)-[r2:EMITIDA_POR]->(f:Fuente)
RETURN n, r1, e, r2, f
LIMIT 10
```

### 4.2 Consulta explicativa de una normativa específica:
**Mostrar clasificación IA, explicación, reglas activadas y evidencia textual asociada.**

Buscamos los nombres de las normativas relevantes

In [22]:
# Consulta rápida para ver los nombres reales de tus normativas relevantes
q_nombres = """
MATCH (n:Relevante)
RETURN n.nombre AS Nombre_Real
LIMIT 5
"""
df_nombres = pd.DataFrame([r.data() for r in session.run(q_nombres)])
df_nombres

                               Nombre_Real
0  Circular N° 12 del 30 de Enero del 2025
1  Circular N° 19 del 06 de Marzo del 2025
2   Circular N° 2 del 02 de Enero del 2025
3  Circular N° 32 del 17 de Abril del 2025
4  Circular N° 33 del 17 de Abril del 2025

In [23]:
q2 = """
MATCH (n:Normativa {nombre: $nombre_buscar})
MATCH (n)-[:TIENE_EXPLICACION]->(e:ExplicacionIA)
OPTIONAL MATCH (n)-[:ACTIVA_REGLA]->(r:ReglaDeNegocio)
OPTIONAL MATCH (n)-[:RESPALDADA_POR]->(ev:EvidenciaTextual)
RETURN n.nombre AS Normativa, 
       labels(n) AS Clasificacion,
       e.texto AS Explicacion, 
       collect(DISTINCT r.nombre) AS Reglas_Activadas, 
       collect(DISTINCT ev.texto) AS Evidencias_Encontradas
"""
df2 = pd.DataFrame([r.data() for r in session.run(q2, nombre_buscar="Circular N° 12 del 30 de Enero del 2025")])
df2

,Normativa,Clasificacion,Explicacion,Reglas_Activadas,Evidencias_Encontradas
0,Circular N° 12 del 30 de Enero del 2025,"[Normativa, Circular, Relevante, ExplicacionValida]","La normativa aborda modificaciones en la Ley sobre Impuesto a las Ventas y Servicios (LIVS) que afectan el cumplimiento tributario, incluyendo cambios en la territorialidad de servicios prestados en forma remota, el régimen de tributación simplificada para contribuyentes no domiciliados ni residentes en Chile, y la fiscalización especial previa en el contexto de devoluciones de impuestos. Estos temas están directamente relacionados con el cumplimiento tributario y el comercio electrónico, lo cual es relevante para un sistema de cumplimiento normativo automatizado en una fintech.","[Contiene 'comercio electrónico', Contiene 'POS', Contiene 'inicio de actividades', Contiene 'cumplimiento tributario']","[Se detectó la palabra clave: comercio electrónico, Se detectó la palabra clave: pos, Se detectó la palabra clave: inicio de actividades, Se detectó la palabra clave: cumplimiento tributario]"

**Probamos consulta en Neo4j Browser**

```cypher
MATCH (n:Normativa {nombre: "Circular N° 12 del 30 de Enero del 2025"})-[r1:TIENE_EXPLICACION]->(e:ExplicacionIA)
OPTIONAL MATCH (n)-[r2:ACTIVA_REGLA]->(r:ReglaDeNegocio)
OPTIONAL MATCH (n)-[r3:RESPALDADA_POR]->(ev:EvidenciaTextual)
RETURN n, r1, e, r2, r, r3, ev
```

### 4.3 Consulta de normativas relevantes con respaldo de negocio:
**Identificar normativas relevantes que activan reglas de negocio y cuentan con evidencia textual.**

In [24]:
q3 = """
MATCH (n:Relevante)-[:ACTIVA_REGLA]->(r:ReglaDeNegocio)
MATCH (n)-[:RESPALDADA_POR]->(ev:EvidenciaTextual)
RETURN n.nombre AS Normativa, 
       count(DISTINCT r) AS Cantidad_Reglas, 
       collect(DISTINCT r.nombre) AS Reglas
"""
df3 = pd.DataFrame([r.data() for r in session.run(q3)])
df3

,Normativa,Cantidad_Reglas,Reglas
0,Circular N° 12 del 30 de Enero del 2025,4,"[Contiene 'comercio electrónico', Contiene 'POS', Contiene 'inicio de actividades', Contiene 'cumplimiento tributario']"
1,Circular N° 19 del 06 de Marzo del 2025,3,"[Contiene 'POS', Contiene 'medios de pago electrónicos', Contiene 'cumplimiento tributario']"
2,Circular N° 2 del 02 de Enero del 2025,4,"[Contiene 'operadores y administradores', Contiene 'POS', Contiene 'inicio de actividades', Contiene 'cumplimiento tributario']"
3,Circular N° 32 del 17 de Abril del 2025,3,"[Contiene 'POS', Contiene 'inicio de actividades', Contiene 'cumplimiento tributario']"
4,Circular N° 33 del 17 de Abril del 2025,5,"[Contiene 'comercio electrónico', Contiene 'POS', Contiene 'inicio de actividades', Contiene 'cumplimiento tributario', Contiene 'boleta']"
5,Circular N° 38 del 30 de Abril del 2025,4,"[Contiene 'POS', Contiene 'medios de pago electrónicos', Contiene 'inicio de actividades', Contiene 'cumplimiento tributario']"
6,Circular N° 39 del 30 de Abril del 2025,5,"[Contiene 'comercio electrónico', Contiene 'POS', Contiene 'medios de pago electrónicos', Contiene 'inicio de actividades', Contiene 'cumplimiento tributario']"
7,Resolución Exenta SII N° 11 del 17 de Enero del 2025,3,"[Contiene 'POS', Contiene 'inicio de actividades', Contiene 'cumplimiento tributario']"
8,Resolución Exenta SII N° 12 del 17 de Enero del 2025,4,"[Contiene 'POS', Contiene 'medios de pago electrónicos', Contiene 'cumplimiento tributario', Contiene 'boleta']"
9,Resolución Exenta SII N° 14 del 30 de Enero del 2025,2,"[Contiene 'POS', Contiene 'cumplimiento tributario']"
10,Resolución Exenta SII N° 18 del 13 de Febrero del 2025,2,"[Contiene 'cumplimiento tributario', Contiene 'boleta']"
11,Resolución Exenta SII N° 20 del 20 de Febrero del 2025,1,[Contiene 'boleta']
12,Resolución Exenta SII N° 26 del 24 de Febrero del 2025,1,[Contiene 'boleta']
13,Resolución Exenta SII N° 44 del 07 de Abril del 2025,4,"[Contiene 'POS', Contiene 'medios de pago electrónicos', Contiene 'registro de venta', Contiene 'boleta']"
14,Resolución Exenta SII N° 53 del 29 de Abril del 2025,3,"[Contiene 'POS', Contiene 'medios de pago electrónicos', Contiene 'boleta']"
15,Resolución Exenta SII N° 63 del 22 de Mayo del 2025,3,"[Contiene 'POS', Contiene 'cumplimiento tributario', Contiene 'registro de compra']"
16,Resolución Exenta SII N° 69 del 19 de Junio del 2025,3,"[Contiene 'POS', Contiene 'inicio de actividades', Contiene 'cumplimiento tributario']"
17,Resolución Exenta SII N° 71 del 19 de Junio del 2025,2,"[Contiene 'POS', Contiene 'cumplimiento tributario']"
18,Resolución Exenta SII N° 77 del 26 de Junio del 2025,4,"[Contiene 'POS', Contiene 'inicio de actividades', Contiene 'cumplimiento tributario', Contiene 'boleta']"
19,Resolución Exenta SII N° 79 del 26 de Junio del 2025,5,"[Contiene 'operadores y administradores', Contiene 'POS', Contiene 'medios de pago electrónicos', Contiene 'inicio de actividades', Contiene 'cumplimiento tributario']"

**Probamos consulta en Neo4j Browser**

```cypher
MATCH (n:Relevante)-[r1:ACTIVA_REGLA]->(r:ReglaDeNegocio)
MATCH (n)-[r2:RESPALDADA_POR]->(ev:EvidenciaTextual)
RETURN n, r1, r, r2, ev
```

### 4.4 Consulta de posibles inconsistencias:
**Detectar No Relevantes que activan reglas de negocio, o Relevantes que no activan reglas.**

In [25]:
q4 = """
MATCH (n:Normativa)
WHERE (n:NoRelevante AND (n)-[:ACTIVA_REGLA]->()) 
   OR (n:Relevante AND NOT (n)-[:ACTIVA_REGLA]->())
RETURN n.nombre AS Normativa_Sospechosa, 
       labels(n) AS Clasificacion_IA, 
       n.descripcion AS Descripcion
"""
df4 = pd.DataFrame([r.data() for r in session.run(q4)])
df4

,Normativa_Sospechosa,Clasificacion_IA,Descripcion
0,Circular N° 10 del 30 de Enero del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]",Imparte instrucciones sobre las modificaciones introducidas por la Ley N° 21.713 al artículo 41 E de la Ley sobre Impuesto a la Renta. Deja sin efecto la Circular N° 29 de 2013.
1,Circular N° 11 del 30 de Enero del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]","Imparte instrucciones sobre las modificaciones introducidas por la Ley N° 21.713 a los artículos 10, 41 G y 41 H, todos de la Ley sobre Impuesto a la Renta. Modifica y complementa las Circulares N° 14 de 2014, N° 12 de 2015, y N° 40 de 2016"
2,Circular N° 13 del 07 de Febrero del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]","Imparte instrucciones sobre el artículo 100 sexies del Código Tributario, incorporado por la Ley N° 21.713."
3,Circular N° 14 del 10 de Febrero del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]",Tablas de impuesto único de segunda categoría para el mes de marzo de 2025 e información adicional relacionada con dicho tributo.
4,Circular N° 18 del 21 de Febrero del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]","Imparte instrucciones sobre la competencia de las Unidades del Servicio para realizar actuaciones que indica de conformidad con las disposiciones del N° 11 de la letra B) del artículo 6°; inciso primero del artículo 65 bis y artículo 65 ter, todos del Código Tributario. Complementa Circular N° 41 de 2015."
...,...,...,...
85,Resolución Exenta SII N° 80 del 26 de Junio del 2025,"[Normativa, NoRelevante, RequiereRevision, Resolucion]",Establece procedimiento para presentar la solicitud de no ser notificado por correo electrónico en las situaciones que prevé el inciso primero del artículo 11 del Código Tributario.
86,Resolución Exenta SII N° 81 del 30 de Junio del 2025,"[Normativa, NoRelevante, RequiereRevision, Resolucion]","Modifica fecha de entrada en vigencia de la Resolución Exenta SIIi N°41 de 2025, que dispone forma de suscripción de la Declaración Jurada exigida por las circulares N° 39 de 1991 y N° 27 de 2007."
87,Resolución Exenta SII N° 82 del 03 de Julio del 2025,"[Normativa, NoRelevante, RequiereRevision, Resolucion]","Aprueba Convenio de Intercambio de Información y Colaboración entre la Unidad Administradora de los Tribunales Tributarios y Aduaneros, y del Tribunal de Contratación Pública y el Servicio de Impuestos Internos."
88,Resolución Exenta SII N° 83 del 03 de Julio del 2025,"[Normativa, NoRelevante, RequiereRevision, Resolucion]",Autoriza como receptor electrónico de documentos tributarios electrónicos a organismos públicos que se indican.
89,Circular N° 1 del 02 de Enero del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]",Imparte instrucciones sobre normas del Código Tributario en materia de aplicación de reajustes e intereses moratorios tras las modificaciones introducidas por la Ley N° 21.713. Modifica la Circular N° 9 de 1988.

**Probamos consulta en Neo4j Browser**

```cypher
MATCH (n:Normativa)
WHERE (n:NoRelevante AND (n)-[:ACTIVA_REGLA]->()) 
   OR (n:Relevante AND NOT (n)-[:ACTIVA_REGLA]->())
OPTIONAL MATCH (n)-[r1:ACTIVA_REGLA]->(r:ReglaDeNegocio)
OPTIONAL MATCH (n)-[r2:TIENE_EXPLICACION]->(e:ExplicacionIA)
RETURN n, r1, r, r2, e
```

### 4.5 Consulta de revisión humana: 
**Identificar normativas con explicación débil, insuficiente o poco alineada con las reglas de negocio.**

In [26]:
q5 = """
MATCH (n:RequiereRevision)-[:TIENE_EXPLICACION]->(e:ExplicacionIA)
RETURN n.nombre AS Normativa, 
       labels(n) AS Etiquetas_Actuales, 
       e.texto AS Explicacion_IA
"""
df5 = pd.DataFrame([r.data() for r in session.run(q5)])
df5

,Normativa,Etiquetas_Actuales,Explicacion_IA
0,Circular N° 10 del 30 de Enero del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]","No cumple reglas de negocio. La normativa se centra en precios de transferencia y operaciones transfronterizas, sin relación directa con los temas especificados como boletas, comprobantes electrónicos, registro de compra, registro de venta, cumplimiento tributario, inicio de actividades, medios de pago electrónicos, POS, operadores y administradores, o comercio electrónico."
1,Circular N° 11 del 30 de Enero del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]","No cumple reglas de negocio. La normativa se centra en modificaciones a la Ley sobre Impuesto a la Renta, específicamente en temas de intercambio de información fiscal y control de entidades extranjeras, sin abordar directamente los temas definidos como relevantes para el sistema de cumplimiento normativo automatizado de la fintech."
2,Circular N° 13 del 07 de Febrero del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]",No cumple reglas de negocio.
3,Circular N° 14 del 10 de Febrero del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]","La normativa se centra en las tablas de impuesto único de segunda categoría y no aborda ninguno de los temas específicos relacionados con el cumplimiento tributario automatizado de una fintech, como boletas, comprobantes electrónicos, registros de compra o venta, medios de pago electrónicos, entre otros."
4,Circular N° 18 del 21 de Febrero del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]","La normativa se centra en la competencia de las unidades del Servicio de Impuestos Internos (SII) para realizar actuaciones de fiscalización y procedimientos administrativos, incluyendo el uso de medios electrónicos para notificaciones y comunicaciones. No aborda directamente temas como boletas, comprobantes electrónicos, registros de compra o venta, cumplimiento tributario automatizado, inicio de actividades, medios de pago electrónicos, POS, operadores y administradores, o comercio electrónico."
...,...,...,...
85,Resolución Exenta SII N° 80 del 26 de Junio del 2025,"[Normativa, NoRelevante, RequiereRevision, Resolucion]","La normativa se centra en el procedimiento para solicitar no ser notificado por correo electrónico, lo cual no se relaciona directamente con los temas definidos como relevantes para el sistema de cumplimiento normativo automatizado de la fintech. No cumple reglas de negocio."
86,Resolución Exenta SII N° 81 del 30 de Junio del 2025,"[Normativa, NoRelevante, RequiereRevision, Resolucion]","La normativa se centra en modificar la fecha de entrada en vigencia de una resolución relacionada con la suscripción de declaraciones juradas para transacciones electrónicas de importación, lo cual no se alinea directamente con los temas específicos de boletas, comprobantes electrónicos, registro de compra, registro de venta, cumplimiento tributario, inicio de actividades, medios de pago electrónicos, POS, operadores y administradores, o comercio electrónico definidos como relevantes."
87,Resolución Exenta SII N° 82 del 03 de Julio del 2025,"[Normativa, NoRelevante, RequiereRevision, Resolucion]","La normativa se centra en un convenio de intercambio de información y colaboración entre el Servicio de Impuestos Internos y la Unidad Administradora de los Tribunales Tributarios y Aduaneros, y del Tribunal de Contratación Pública. No aborda directamente temas relacionados con boletas, comprobantes electrónicos, registros de compra o venta, cumplimiento tributario, inicio de actividades, medios de pago electrónicos, POS, operadores y administradores, o comercio electrónico."
88,Resolución Exenta SII N° 83 del 03 de Julio del 2025,"[Normativa, NoRelevante, RequiereRevision, Resolucion]","La normativa se centra en autorizar a organismos públicos como receptores de documentos tributarios electrónicos, lo cual no afecta directamente los procesos generales de cumplimiento automatizado de la fintech en los temas especificados. No cumple reglas de negocio."
89,Circular N° 1 del 02 de Enero del 2025,"[Normativa, Circular, NoRelevante, RequiereRevision]","La normativa se centra en la aplicación de reajustes e intereses moratorios sobre impuestos o contribuciones adeudadas, lo cual no se relaciona directamente con los temas definidos como relevantes, tales como boletas, comprobantes electrónicos, registro de compra o venta, cumplimiento tributario automatizado, medios de pago electrónicos, POS, operadores y administradores, o comercio electrónico."

**Probamos en Neo4j Browser**

```cypher
MATCH (n:RequiereRevision)-[r:TIENE_EXPLICACION]->(e:ExplicacionIA)
RETURN n, r, e
```

In [27]:
# Consulta de control: Cuenta cuántos nodos hay por cada etiqueta existente
q_control = """
MATCH (n:Normativa)
RETURN labels(n) AS Etiquetas, count(n) AS Total
"""
df_control = pd.DataFrame([r.data() for r in session.run(q_control)])
df_control

                                                 Etiquetas  Total
0     [Normativa, Circular, NoRelevante, RequiereRevision]     26
1      [Normativa, Circular, Relevante, ExplicacionValida]      7
2    [Normativa, Circular, NoRelevante, ExplicacionValida]     13
3   [Normativa, NoRelevante, RequiereRevision, Resolucion]     64
4    [Normativa, Relevante, ExplicacionValida, Resolucion]     13
5  [Normativa, NoRelevante, ExplicacionValida, Resolucion]      6

## 5. Auditoria Simulada

### 5.1 Tabla de Auditoría de Iniciativas (Evaluación del Agente IA)

De acuerdo a los requerimientos del laboratorio, se seleccionan 5 normativas clave integradas en el grafo de Neo4j (tanto clasificadas como *Relevantes* como *No Relevantes*) para contrastar la decisión del modelo automatizado con el criterio experto del grupo.

La siguiente celda realiza una consulta Cypher dinámica para extraer el estado del grafo y le añade las columnas de **Juicio del Grupo** y **Justificación** requeridas para la auditoría humana simulada:

In [28]:
# 1. Definir explícitamente las 5 normativas a auditar presentes en el dataset
normativas_a_auditar = [
    "Circular N° 12 del 30 de Enero del 2025",
    "Circular N° 19 del 06 de Marzo del 2025",
    "Resolución Exenta SII N° 77 del 26 de Junio de 2025",
    "Resolución Exenta SII N° 67 del 12 de Junio de 2025",
    "Resolución Exenta SII N° 58 del 06 de Mayo del 2025"
]

# 2. Consulta Cypher para extraer la información estructurada desde Neo4j
query_auditoria = """
MATCH (n:Normativa)
WHERE n.nombre IN $nombres
MATCH (n)-[:TIENE_EXPLICACION]->(e:ExplicacionIA)
OPTIONAL MATCH (n)-[:ACTIVA_REGLA]->(r:ReglaDeNegocio)
OPTIONAL MATCH (n)-[:RESPALDADA_POR]->(ev:EvidenciaTextual)
RETURN n.nombre AS Normativa_Revisada,
       [lbl IN labels(n) WHERE lbl <> 'Normativa'] AS Clasificacion_IA,
       collect(DISTINCT r.nombre) AS Reglas_Activadas,
       collect(DISTINCT ev.texto) AS Evidencia_Textual
"""

res_auditoria = session.run(query_auditoria, nombres=normativas_a_auditar)
df_auditoria = pd.DataFrame([r.data() for r in res_auditoria])

# 3. Mapeo del Juicio Humano del Grupo y Justificación para cada iniciativa
evaluacion_humana = {
    "Circular N° 12 del 30 de Enero del 2025": {
        "Juicio": "Validada",
        "Justificacion": "La clasificación de la IA es correcta. El documento aborda explícitamente modificaciones operacionales críticas de comercio electrónico y terminales POS."
    },
    "Circular N° 19 del 06 de Marzo del 2025": {
        "Juicio": "Validada",
        "Justificacion": "Clasificación consistente con el negocio. Activa de manera correcta las reglas de medios de pago electrónicos basándose en el cuerpo normativo."
    },
    "Resolución Exenta SII N° 77 del 26 de Junio de 2025": {
        "Juicio": "Validada",
        "Justificacion": "El agente IA identificó con precisión la relación con los procesos de inicio de actividades y cumplimiento tributario vigentes."
    },
    "Resolución Exenta SII N° 67 del 12 de Junio de 2025": {
        "Juicio": "Validada",
        "Justificacion": "Correctamente catalogada como No Relevante. Su enfoque está limitado estrictamente al deber de reserva interna institucional del servicio."
    },
    "Resolución Exenta SII N° 58 del 06 de Mayo del 2025": {
        "Juicio": "Requiere más antecedentes",
        "Justificacion": "Aunque la IA la clasificó como No Relevante por falta de palabras clave explícitas, la descripción técnica de los parámetros objetivos amerita un análisis legal manual extendido."
    }
}

# 4. Incorporar las columnas del criterio humano al DataFrame de resultados
df_auditoria['Juicio del Grupo'] = df_auditoria['Normativa_Revisada'].map(lambda x: evaluacion_humana.get(x, {}).get('Juicio', 'No Evaluado'))
df_auditoria['Justificación'] = df_auditoria['Normativa_Revisada'].map(lambda x: evaluacion_humana.get(x, {}).get('Justificacion', ''))

# Reordenar columnas para cumplir exactamente con la estructura solicitada
columnas_ordenadas = ['Normativa_Revisada', 'Clasificacion_IA', 'Reglas_Activadas', 'Evidencia_Textual', 'Juicio del Grupo', 'Justificación']
df_auditoria = df_auditoria[columnas_ordenadas]

# 5. Desplegar la matriz de auditoría
pd.set_option('display.max_colwidth', None)
df_auditoria

,Normativa_Revisada,Clasificacion_IA,Reglas_Activadas,Evidencia_Textual,Juicio del Grupo,Justificación
0,Circular N° 12 del 30 de Enero del 2025,"[Circular, Relevante, ExplicacionValida]","[Contiene 'comercio electrónico', Contiene 'POS', Contiene 'inicio de actividades', Contiene 'cumplimiento tributario']","[Se detectó la palabra clave: comercio electrónico, Se detectó la palabra clave: pos, Se detectó la palabra clave: inicio de actividades, Se detectó la palabra clave: cumplimiento tributario]",Validada,La clasificación de la IA es correcta. El documento aborda explícitamente modificaciones operacionales críticas de comercio electrónico y terminales POS.
1,Circular N° 19 del 06 de Marzo del 2025,"[Circular, Relevante, ExplicacionValida]","[Contiene 'POS', Contiene 'medios de pago electrónicos', Contiene 'cumplimiento tributario']","[Se detectó la palabra clave: pos, Se detectó la palabra clave: medios de pago electrónicos, Se detectó la palabra clave: cumplimiento tributario]",Validada,Clasificación consistente con el negocio. Activa de manera correcta las reglas de medios de pago electrónicos basándose en el cuerpo normativo.
2,Resolución Exenta SII N° 58 del 06 de Mayo del 2025,"[NoRelevante, RequiereRevision, Resolucion]",[Contiene 'POS'],[Se detectó la palabra clave: pos],Requiere más antecedentes,"Aunque la IA la clasificó como No Relevante por falta de palabras clave explícitas, la descripción técnica de los parámetros objetivos amerita un análisis legal manual extendido."

**Nota de Integración:** A través de esta simulación se logra validar el comportamiento del agente de IA en un 80% de aciertos directos (*Validadas*), aislando un caso crítico (*Requiere más antecedentes*) donde las reglas por palabras clave resultaron insuficientes frente a la semántica compleja de la resolución.